version: "2"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/data/db:/data/db"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/c/Users/bookstore/redis/data:/data"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment: 
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS= -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "/c/Users/bookstore/esdata1:/usr/share/elasticsearch/data"

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile 
    image: nodeapp
    ports:
      - "2000:2000"
      - "3000:3000"
    volumes:
      - "/c/Users/bookstore/:/opt/app"

volumes:
  esdata1:
    driver: local

      