# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  general:
    branches:
      ignore:
        - auth
        - booksCategory
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      - image: mongo
        environment:
          DATABASE_URL: mongodb://localhost/note
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/src

    steps:
      - checkout

      - run: echo "Tests starting!!!"

      # Download and cache dependencies
      - run: npm install

      # run tests!
      - run: npm run test



